---
name: test
on:
  push:
    branches:
      - master
      - use-sasl-auth-2
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['23', '24', '25']
        rebar3: ['3.16.1']
    steps:
      - uses: actions/checkout@v2
      - name: Install system deps 
        run:
          sudo apt-get update && apt-get install -y \
          autoconf \
          automake \
          autotools-dev \
          build-essential \
          g++ \
          gcc \
          libffi-dev \
          make \
          libkrb5-dev \
          libsasl2-dev \
          libsasl2-modules-gssapi-mit
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - name: Static analysis
        run: rebar3 dialyzer
      - name: Common Tests
        run: rebar3 test
